<?php

include_once("/var/www/dayplan/model/bd.php");
include_once("/var/www/dayplan/model/user.php");
include_once("/var/www/dayplan/dao/userdao.php");
include_once("/var/www/dayplan/controller/userController.php");

include_once("/var/www/dayplan/model/dayplan.php");
include_once("/var/www/dayplan/dao/dayplandao.php");
include_once("/var/www/dayplan/controller/dayplanController.php");

require '/var/www/dayplan/lib/PHPMailer/PHPMailerAutoload.php';

session_start();

$bbdd = DB::getInstance();
$bbdd->stablishUTF8();

$dayplan = new Dayplan();

$dayplanDAO = new DayplanDAO($dayplan);

//$users = array();

$result = $dayplanDAO->notSentDayplans("admin", "it");

$count = 0;

$row = mysqli_fetch_assoc($result);

$mail = new PHPMailer;

//$mail->SMTPDebug = 3;                               	// Enable verbose debug output

$mail->isSMTP();                                      	// Set mailer to use SMTP
$mail->Host = 'smtp.office365.com';  					// Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               	// Enable SMTP authentication
$mail->Username = 'alerts@mlcomponents.com';          	// SMTP username
$mail->Password = 'MoreNiko19';                         	// SMTP password
$mail->SMTPSecure = 'tls';                            	// Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    	// TCP port to connect to

$mail->setFrom('alerts@mlcomponents.com', 'DELAYED DAYPLANS');

while($row = mysqli_fetch_assoc($result)){
	$mail->addBCC($row["email"], $row["name"]);
	$count ++;
}

$mail->isHTML(true);

// Set email format to HTML

$mail->Subject = 	'Delayed dayplan';
$mail->Body    = 	"WELL THIS IS WEIRD BUT IF YOU GOT THIS MESSAGE MEANS THAT YOU NEED TO SEND THE DAYPLAN BECAUSE THE TIME IS OVER! IF YOU GOT THIS MESSAGE IS BECAUSE YOU ARE TESTING THE NEW DAYPLAN SYSTEM, IF YOU DONT WANT TO GOT THIS EMAILS IN THE FUTURE, SEND AN EMAIL TO: <a href='mailto:juancarlos@mlcomponents.com'>Juan Carlos Paz (IT - WEB DEVELOPER)</a><b><p>This is an autogenerated message from the ML Components new dayplan mail system.</p></b><br>";
$mail->AltBody = 'This is an autogenerated message from the ML Components new dayplan mail system.';

if(!$mail->send()) {
    $result = '<div class="alert alert-danger">Sorry there was an error sending your message. Please try again later: </div><br>' . $mail->ErrorInfo;
} else {
	$result = '<div class="alert alert-success">Thank You! I will be in touch</div>';
}

echo $result;

?>